#    Copyright 2025 Kubotal
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Image and chart registry — Must be set via dev.env or from environment.
# Intentionally empty in this makefile, as we want user to set REGISTRY
# explicitly. Targets that need it depend on `check-registry`, which fails with
# a clear message when it is unset.
# Main official repository is quay.io/kubauth
REGISTRY ?= ""


# Per-developer overrides (git-ignored, optional).
# The leading '-' makes a missing file a silent no-op, so this never breaks.
-include dev.env


# The product VERSIONS below are intentionally NOT overridable from dev.env or from environment.
# They are code-bound and git-controlled (see the ':=' assignment type).

APP_VERSION ?= 0.2.1-snapshot
HELM_VERSION ?= 0.2.1-snapshot

IMG_REPO := $(REGISTRY)/exec/kubauth-apiserver

HELM_DOCKER_REPO := $(REGISTRY)/charts

# To authenticate for pushing in quay repo (img) (Use encrypted password):
# docker login quay.io

# To authenticate for pushing in quay repo (helm):
# helm registry login quay.io

# To authenticate for pushing in github repo:
# echo $GITHUB_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin


BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
#SHELL = /usr/bin/env bash -o pipefail
#.SHELLFLAGS = -ec

#.PHONY: all
#all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: version
version: ## Set version in binary
	@echo "// Generated by Makefile\n\npackage global\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/global/version_.go


##@ Build


##@ Build

.PHONY: check-registry
check-registry: ## Fail with a clear message if REGISTRY is not set
	@if [ -z "$(strip $(REGISTRY))" ]; then \
		echo "ERROR: REGISTRY is not set."; \
		echo "Set it in dev.env, export it in your environment, or pass it on the command line, e.g.:"; \
		echo "    make $(or $(MAKECMDGOALS),<target>) REGISTRY=quay.io/my-organization"; \
		exit 1; \
	fi

.PHONY: display
display:  ## Display current config values
	@echo "---------"
	@echo "REGISTRY: $(REGISTRY)"
	@echo "APP_VERSION: $(APP_VERSION)"
	@echo "HELM_VERSION: $(HELM_VERSION)"
	@echo "BUILD_TS: $(BUILD_TS)"
	@echo "---------"


.PHONY: build
build:  ## Build kubauth-apiserver binaries
	CGO_ENABLED=0 go build -o bin/kubauth-apiserver main.go

##@ Docker

.PHONY: docker
docker: version display docker-build docker-push  ## Build controller docker image and push

.PHONY: docker-build
docker-build: check-registry version ## Build docker image with the manager.
	$(CONTAINER_TOOL) build -t $(IMG_REPO):$(APP_VERSION) .

.PHONY: docker-push
docker-push: check-registry ## Push docker image with the manager.
	$(CONTAINER_TOOL) push $(IMG_REPO):$(APP_VERSION)


.PHONY: docker-ubuntu
docker-ubuntu: version display docker-ubuntu-build docker-ubuntu-push  ## Build controller docker image using Ubuntu 22.04  and push

.PHONY: docker-ubuntu-build
docker-ubuntu-build: check-registry version ## Build docker image using Ubuntu 22.04 as base
	$(CONTAINER_TOOL) build --build-arg RUNTIME_BASE=ubuntu:22.04 -t $(IMG_REPO):$(APP_VERSION)-ubuntu .

.PHONY: docker-ubuntu-push
docker-ubuntu-push: check-registry ## Push docker image using Ubuntu 22.04  with the manager.
	$(CONTAINER_TOOL) push $(IMG_REPO):$(APP_VERSION)-ubuntu



# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: check-registry display version  ## Build and push docker image for the manager for cross-platform support
	- $(CONTAINER_TOOL) buildx create --name kubauth-apiserver-builder --driver=docker-container
	- $(CONTAINER_TOOL) buildx build --builder kubauth-apiserver-builder --push --platform=$(PLATFORMS) --tag $(IMG_REPO):$(APP_VERSION) -f Dockerfile .
	- $(CONTAINER_TOOL) buildx rm kubauth-apiserver-builder


##@ Helm

# ---------------------------

define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: kubauth-apiserver
version: $(HELM_VERSION)
appVersion: $(APP_VERSION)
description: "Kubauth-apiserver: A kubernetes OIDC integration tool (API server configuration support)"
keywords:
  - kubernetes
  - kubauth
  - authentication
  - oidc
  - kubectl
sources:
  - https://github.com/kubauth/kubauth-apiserver
maintainers:
  - name: kubauth
    url: https://github.com/kubauth
annotations:
  kubotal_image_repository: $(IMG_REPO)
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: check-registry ## Generate the helm/kubauth-apiserver/Chart.yaml
	echo "$$CHART_YAML" >./helm/kubauth-apiserver/Chart.yaml

.PHONY: chart
chart: check-registry display chart-yaml ## Build and push kubauth-apiserver helm chart
	cd ./helm && helm package -d ./../tmp kubauth-apiserver && helm push ./../tmp/kubauth-apiserver-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}

# ---------------------------
##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

## Tool Binaries
KUBECTL ?= kubectl
