#    Copyright 2025 Kubotal
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

APP_VERSION ?= 0.2.1-snapshot
HELM_KUBAUTH_APISERVER_VERSION ?= 0.2.1-snapshot

DOCKER_TAG=${APP_VERSION}

IMG ?= quay.io/kubauth/exec/kubauth-apiserver:${DOCKER_TAG}

IMG_UBUNTU ?= quay.io/kubauth/exec/kubauth-apiserver:${DOCKER_TAG}-ubuntu

HELM_DOCKER_REPO := quay.io/kubauth/charts

# To authenticate for pushing in quay repo (img) (Use encrypted password):
# docker login quay.io

# To authenticate for pushing in quay repo (helm):
# helm registry login quay.io

# To authenticate for pushing in github repo:
# echo $GITHUB_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin


BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
#SHELL = /usr/bin/env bash -o pipefail
#.SHELLFLAGS = -ec

#.PHONY: all
#all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: version
version: ## Set version in binary
	@echo "// Generated by Makefile\n\npackage global\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/global/version_.go


##@ Build

.PHONY: build
build:  ## Build kubauth-apiserver binaries
	CGO_ENABLED=0 go build -o bin/kubauth-apiserver main.go


##@ Docker

.PHONY: docker
docker: version docker-build docker-push  ## Build controller docker image and push

.PHONY: docker-build
docker-build: version ## Build docker image with the manager.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push ${IMG}


.PHONY: docker-ubuntu
docker-ubuntu: version docker-ubuntu-build docker-ubuntu-push  ## Build controller docker image using Ubuntu 22.04  and push

.PHONY: docker-ubuntu-build
docker-ubuntu-build: version ## Build docker image using Ubuntu 22.04 as base
	$(CONTAINER_TOOL) build --build-arg RUNTIME_BASE=ubuntu:22.04 -t ${IMG_UBUNTU} .

.PHONY: docker-ubuntu-push
docker-ubuntu-push: ## Push docker image using Ubuntu 22.04  with the manager.
	$(CONTAINER_TOOL) push ${IMG_UBUNTU}



# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
#PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: version  ## Build and push docker image for the manager for cross-platform support
	- $(CONTAINER_TOOL) buildx create --name kubauth-apiserver-builder --driver=docker-container
	- $(CONTAINER_TOOL) buildx build --builder kubauth-apiserver-builder --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile .
	- $(CONTAINER_TOOL) buildx rm kubauth-apiserver-builder


##@ Helm

# ---------------------------

define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: kubauth-apiserver
version: $(HELM_KUBAUTH_APISERVER_VERSION)
appVersion: $(APP_VERSION)
description: "Kubauth-apiserver: A kubernetes OIDC integration tool (API server configuration support)"
keywords:
  - kubernetes
  - kubauth
  - authentication
  - oidc
  - kubectl
sources:
  - https://github.com/kubauth/kubauth-apiserver
maintainers:
  - name: kubauth
    url: https://github.com/kubauth
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: ## Generate the helm/kubauth-apiserver/Chart.yaml
	echo "$$CHART_YAML" >./helm/kubauth-apiserver/Chart.yaml

.PHONY: chart
chart: chart-yaml ## Build and push kubauth-apiserver helm chart
	cd ./helm && helm package -d ./../tmp kubauth-apiserver && helm push ./../tmp/kubauth-apiserver-${HELM_KUBAUTH_APISERVER_VERSION}.tgz oci://${HELM_DOCKER_REPO}

# ---------------------------
##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

## Tool Binaries
KUBECTL ?= kubectl
