---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "kubauth-kit.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clusterRoleName" . }}
  labels:
    {{- include "kubauth-kit.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterRoleName" . }}-{{ include "serviceAccountName" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "kubauth-kit.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccountName" . }}
    namespace: {{ .Release.Namespace}}

